import './globals.css';
import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn([inter.className, 'p-4'])}>
        <main className="min-h-[400px]">{children}</main>
        <footer className="mt-8 flex flex-col items-center justify-center gap-4 border-t pt-8">
          <p className="text-xs">
            Built with &hearts; using <a href="https://nextjs.org/">Next.js</a>{' '}
            on <a href="https://vercel.org">&#x25B2; Vercel</a> by{' '}
            <a href="https://joshdavenport.co.uk">Josh Davenport-Smith</a>
          </p>
          <a href="https://www.buymeacoffee.com/joshdprts" target="_blank">
            <img
              src="https://cdn.buymeacoffee.com/buttons/v2/default-blue.png"
              alt="Buy Me A Coffee"
              className="h-[36px] w-[130px]"
            />
          </a>
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
